### PR TITLE
Updated dependencies to latest

### PR DESCRIPTION
**Pull request by shankarsengalani**
Updated dependencies to latest and code to support it.
Updated Readme

### CODE REVIEW

**Review by davidmason — APPROVED** [review]

**Comment by davidmason** [comment]
@shankar2105 Thanks for the PR - sorry it took so long to merge, got a bit behind on my notifications.

**Comment by karl-run** [comment]
Could you release a new version as well?

**Comment by davidmason** [comment]
Sure, I’ll do a release in the morning - about 10 hours from now.

**Comment by davidmason** [comment]
@karl-run released 2.0.0 https://github.com/davidmason/react-stylable-diff/releases/tag/v2.0.0

**Pull request merged**
